include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/*.gen.dart"

  language:
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Style
    prefer_const_constructors: true
    prefer_final_locals: true
    prefer_single_quotes: true
    avoid_print: true
    omit_local_variable_types: false
    unnecessary_this: true

    # Naming & formatting
    camel_case_types: true
    file_names: true
    constant_identifier_names: false
    library_prefixes: true

    # Error prevention
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_redundant_argument_values: true
    avoid_returning_null_for_future: true
    null_check_on_nullable_type_parameter: true
    parameter_assignments: false
    unnecessary_null_checks: true
    prefer_typing_uninitialized_variables: true

    # Best practices
    use_key_in_widget_constructors: true
    sort_child_properties_last: true
    sort_constructors_first: true
    type_annotate_public_apis: true
    avoid_unnecessary_containers: true

    # Code structure
    avoid_classes_with_only_static_members: false
    prefer_mixin: true
    prefer_const_literals_to_create_immutables: true
    directives_ordering: true
    always_put_required_named_parameters_first: true
    depend_on_referenced_packages: true